[package]
name = "psbtsigner"
version = "0.0.1"
authors = ["Antoine Poinsot <darosior@protonmail.com>"]
edition = "2018"

[dependencies]
revault_tx = { git = "https://github.com/re-vault/revault_tx", features = ["use-serde"] }
base64 = "0.13.0"
